### ISSUE TITLE
Chain Challenge progression

### ISSUE THREAD

**Issue by den-t** [JuniorDev-TGA/CodeChallenges#4]
After mulling over Rio's solution (#3) for a while. Might we worth considering...
Should the original code be updated to something close to that solution? This way challenge takers will be more focused on applying the pattern and/or parametrising the validation, and not on fixing the unwieldy function.

**Comment by kellymarjorie** [comment]
That's a good point, but the point of this particular challenge is to refactor the convoluted code, and learn best practices around writing cleaner code. Changing the function to be able to be reused in other applications and using the design pattern comes afterward if people want to continue with it. We can always make another challenge that focuses just on the pattern for more practice if need be.

**Comment by den-t** [comment]
Got it. Makes total sense.
